name: Publish Python Package to PyPi

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Get tag
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

    - name: Install pypa/build
      env:
        RELEASE_VERSION: ${{ steps.get_tag.outputs.TAG }}
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
